### ISSUE TITLE
[Feature] - Object Storage

### ISSUE THREAD

**Issue by Lvl4Sword** [vultr/ansible-collection-vultr#101]
**Is your feature request related to a problem? Please describe.**
Surfing through https://docs.ansible.com/ansible/latest/collections/vultr/cloud/index.html , it looks like object storage isn't supported currently, unless I misread?

**Describe the solution you'd like**
For object storage to be supported and available via the Ansible collection

**Describe alternatives you've considered**
There aren't any viable alternatives

**Comment by resmo** [comment]
Hi @Lvl4Sword, implemented with #103
