### ISSUE TITLE
[Feature] - Option to skip waiting for instance creation

### ISSUE THREAD

**Issue by Lusitaniae** [vultr/ansible-collection-vultr#119]
When deploying large amount of instances, it's very useful to skip waiting for the instance to become online. 
If it takes 1/2 min per instance to become available, and I'm deploying 100 nodes... its easily 2h of waiting each

while I just want to deploy 100 in one go and wait 2 min to have all online

for comparison see DO module:
https://docs.ansible.com/ansible/latest/collections/community/digitalocean/digital_ocean_droplet_module.html#parameter-wait

**Describe the solution you'd like**
add this flag: 

`wait: true|false`

**Describe alternatives you've considered**

**Additional context**

**Comment by resmo** [comment]
Hi @Lusitaniae, this makes perfectly sense. We are going to implement this in the next release.

**Comment by resmo** [comment]
implemented in #120
