### ISSUE TITLE
[Feature] - Dynamic inventory plugin for existing instances

### ISSUE THREAD

**Issue by resmo** [vultr/ansible-collection-vultr#17]

**Comment by allan-bailey** [comment]
was there a big change from the previous version that this didn't port over?

**Comment by resmo** [comment]
@allan-bailey yes

**Comment by resmo** [comment]
@jasites @biondizzle You're from vultr? Thanks for helping out, but I would appreciate if you could get in touch beforehand about your intention (this issue was assigned to me and I might have started to work on issues assigned to me, that's why I assign issues to me).

Thanks!

**Comment by resmo** [comment]
@biondizzle  okay, so could we agree that we first create a theme here before we start working in the future?

**Comment by biondizzle** [comment]
@resmo works for me! We will start the issue on GitHub.
