### ISSUE TITLE
[Feature] - instance module

### ISSUE THREAD

**Issue by resmo** [vultr/ansible-collection-vultr#18]

**Comment by stuevansuk** [comment]
Any idea on the release date for this? The previous module is broken with instance deployment and this new one does not contain any instance deployment features.

**Comment by resmo** [comment]
I don't have a fixed date, but I am currently working on it and expect it to be ready in the range of days.

**Comment by resmo** [comment]
Please subscribe to #21 to watch the progress.

**Comment by resmo** [comment]
closed by #21
