### ISSUE TITLE
[BUG] - Tags for instances do not reflect properly in ansible-inventory

### ISSUE THREAD

**Issue by binnsr** [vultr/ansible-collection-vultr#41]
**Describe the bug**
An instance provisioned with multiple tags only has one of them in the _instance.tag_ field and there is not _instance.tags_ (or similar) field to handle the rest of the tags assigned. This makes it impossible to coherently organize ansible inventory by tags

**To Reproduce**
1. Provision a server with multiple tags.  Using Terraform, the code would be: **tags = [ "tag1", "tag2", "tag3" ]**
2. Create a basic inventory.yml file with "_plugin: vultr_" as the contents
3. Execute _ansible-inventory -i inventory.yml -host <host created in step1>_
4. Observe that there is a _instance.tag_ result containing one of the 3 tags assigned above.
5. Observe that there are no records with the remaining tags

**Expected behavior**
All tags assigned to the server should be reported by ansible-inventory

$ ansible-inventory --version
ansible-inventory [core 2.13.7]
  config file = /home/rex/.ansible.cfg
  configured module search path = ['/home/rex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rex/venv/ansible_env/3.x/lib/python3.8/site-packages/ansible
  ansible collection location = /home/rex/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rex/venv/ansible_env/3.x/bin/ansible-inventory
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True

**Comment by resmo** [comment]
Hi @binnsr 

Could you provide the `inventory.yml`? Could this be related to the "old" inventory plugin `plugin: vultr`, `plugin: ngine_io.vultr.vultr` using APIv1?

**Comment by binnsr** [comment]
main.tf
`
data "doppler_secrets" "secrets" {
  project = "${var.ctx_doppler_project}"
  config  = "${var.ctx_doppler_config}"
}

data "vultr_ssh_key" "conn_ssh_key" {
  filter {
    name   = "name"
    values = [ data.doppler_secrets.secrets.map.CTX_CONN_RESOURCE_KEY ]
  }
}

resource "vultr_instance" "test_server" {
  count             = 1
  hostname          = "test-server-${count.index}"
  label             = "test-server-${count.index}"
  tags              = [ "tag1", "tag2", "tag3" ]
  plan              = "vc2-1c-1gb"
  os_id             = 387
  region            = "ord"
  ssh_key_ids       = [ "${data.vultr_ssh_key.conn_ssh_key.id}" ]
  activation_email  = false
  enable_ipv6       = false
}
`
inventory.vultr.yml
`plugin: vultr
api_token: "{{ lookup( 'env', 'VULTR_API_TOKEN' ) }}"
attributes:
  - id
  - name
  - tags
  - networks

keyed_groups:
  - prefix: vultr_region
    key: region | lower
  - separator: ""
    key: tag
`
results:
`ansible-inventory -i allservers_inventory.vultr.yml --host test-server-0
{
    "allowed_bandwidth_gb": 1000,
    "ansible_host": "45.76.227.127",
    "auto_backup_enabled": false,
    "cost_per_month": 5.0,
    "current_bandwidth_gb": 0,
    "date_created": "2022-12-08 20:12:29",
    "default_password": "%9Vy13)zvJ#pjvy3",
    "disk": "Virtual 25.00 GB",
    "id": "62490847",
    "internal_ip": "",
    "kvm_url": "https://my.vultr.com/subs/vps/novnc/api.php?data=djJ8TW9Ed3pZQ2VtbFdGMGNmcGx0MDJiOUI5b3J6N3BQMkZ8KylsEPlhqWxIthhwxf8o7YxgRw7mhxoa9zL4oZesrQMdbn3n-4VcA_uG47hL7hzL_-b6wGSxx1uqW9OCeS1HFc8ufhG39qf7qyrPgJKA_oVlZ7iHz3hGRcVSLzUMbAv9m6ZKNbM9wnfZwZcsGU9fgJok75OfQa0nQbV11uuKh4ehgiN-87IqAn1msem-o_WLiWQTJH5YuTTjsrxf4uqT",
    "name": "test-server-0",
    "os": "Ubuntu 20.04 LTS x64",
    "pending_charges": 0.01,
    "power_status": "running",
    "ram": "1024.00 MB",
    "region": "Chicago",
    "server_state": "installingbooting",
    "status": "active",
    "tag": "tag1",
    "v4_gateway": "45.76.226.1",
    "v4_main_ip": "45.76.227.127",
    "v6_main_ip": "",
    "v6_network": "",
    "v6_network_size": "",
    "v6_networks": [],
    "vcpu_count": 1
}`

**Comment by binnsr** [comment]
After executing `ansible-galaxy collection install vultr.cloud` and replacing the plugin line with`plugin: vultr.cloud.vultr` returns this:
```
$ ansible-inventory -i ./allservers_inventory.vultr.yml --graph
[WARNING]:  * Failed to parse /tmp/allservers_inventory.vultr.yml with auto plugin: inventory config '/tmp/allservers_inventory.vultr.yml' specifies unknown plugin
'vultr.cloud.vultr'
[WARNING]:  * Failed to parse /tmp/allservers_inventory.vultr.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /tmp/allservers_inventory.vultr.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character
is reserved to provide a port.
[WARNING]: Unable to parse /tmp/allservers_inventory.vultr.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
@all:
  |--@ungrouped:
```
changing the `plugin:` line back to `plugin: vultr` gets rid of this error.

**Comment by resmo** [comment]
1.4.0 has been released. Use `ansible-galaxy collection install vultr.cloud:==1.4.0` or `ansible-galaxy collection install vultr.cloud --upgrade` to upgrade to release 1.4.0.

**Comment by binnsr** [comment]
@resmo Great!  after testing, the only remaining issue is that the `filter_by_tag` feature doesn't seem to be working.  Has the functionality of that changed? and if so, where can I find current documentation for 1.4.0?

**Comment by resmo** [comment]
The doc will be at https://docs.ansible.com/ansible/latest/collections/vultr/cloud/ once ansible community package has a new release. In the meanwhile the best option is the cli `ansible-doc -t inventory vultr.cloud.vultr` 

There you see an option `filters`

```
- filters
        Filter hosts with Jinja2 templates.
        If not provided, all hosts are added to inventory.
        default: []
        elements: str
        type: list
```
So in your inventory plugin config, adding a filter like:

```yaml
filters:
  - '"production" in vultr_tags' 
```

should filter by a tag. However, another option is to group hosts by tag dynamically:

```yaml
keyed_groups:
  - key: vultr_tags | lower
    prefix: ''
    separator: ''
```

so if you have a host having tag `production` it gets in the group `production` and you can use `--limit production` in your `ansible-playbook` runs.
