### ISSUE TITLE
[Feature] - Instance_info module

### ISSUE THREAD

**Issue by biondizzle** [vultr/ansible-collection-vultr#47]
I need to fetch details about an instance via ansible so I can read it's tags. 

There is only a `vultr_instance` plugin which is designed for create/delete/start/stop sort of things. There doesn't seem to be any way to simply read an instance using it's ID or some other combination of attributes.

**Comment by resmo** [comment]
It seems the `instance_info` module was forgotten to implement. Piece of cake, should be ready this week.
