### ISSUE TITLE
[Feature] - Add support for creating instances from a Snapshot

### ISSUE THREAD

**Issue by astuckey123** [vultr/ansible-collection-vultr#55]
**Is your feature request related to a problem? 
The deprecated ngine_io.vultr allowed you to created instances feeding in a snapshot name.  cloud.vultr.instance does not support the provision of snapshots.  All of our vultr instances are based on custom snapshots, we are no longer able to deploy new servers without this support.

**Describe the solution you'd like**
Ability to provide a snapshot name to create the instance from.

**Describe alternatives you've considered**
Write a custom ansible module to use this part of the Vultr API, or fork this repo to fix.  Thought it best to raise a feature request so that the community benefits.

**Additional context**
The Vultr V2 API supports creation of an instance with a snapshot id:
https://www.vultr.com/api/#operation/create-instance
snapshot_id | string - The Snapshot id to use when deploying the instance.

**Comment by resmo** [comment]
Addressed in PR #56
