### ISSUE TITLE
[Feature] inventory for bare metal hosts

### ISSUE THREAD

**Issue by allan-bailey** [vultr/ansible-collection-vultr#61]
**Is your feature request related to a problem? Please describe.**

Currently (1.7.0) does not support bare metal hosts inventory.

**Describe the solution you'd like**

Add the v2 bare metal API inventory.

**Additional context**
I couldn't find anything in the Issues or PRs, so opening this.

We're using a fair number of vultr hosts managed with ansible and would like to use this plugin for dynamic inventory.

**Comment by resmo** [comment]
Bare metal support has been  implemented via PR #63
Closed by #63
