### ISSUE TITLE
[Feature] State `reinstalled`

### ISSUE THREAD

**Issue by eifelmicha** [vultr/ansible-collection-vultr#65]
**Is your feature request related to a problem? Please describe.**
https://docs.ansible.com/ansible/latest/collections/ngine_io/vultr/vultr_server_module.html#ansible-collections-ngine-io-vultr-vultr-server-module supported reinstallation of existing servers. I like to use this feature in CI pipelines for cost optimization of tasks running only a few minutes.

**Describe the solution you'd like**
Implemented state: `reinstalled` 

**Describe alternatives you've considered**
Old collection, but too much trouble.

**Additional context**
 I couldn't find anything in the Issues or PRs, so opening this.

**Comment by resmo** [comment]
cosed by #66 will be included in the 1.8.0 release published soon.
