### ISSUE TITLE
[Bug] vultr_tags not returned in inventory

### ISSUE THREAD

**Issue by Lvl4Sword** [vultr/ansible-collection-vultr#69]
**Is your feature request related to a problem? Please describe.**
https://docs.ansible.com/ansible/latest/collections/vultr/cloud/vultr_inventory.html has an example using:
```yaml
filters:
  - '"vpc" in vultr_tags'
```
Though apparently this does nothing as vultr_tags isn't available anywhere.

**Describe the solution you'd like**
`vultr_tags` actually being available, so they can be filtered on.

**Describe alternatives you've considered**
?

**Additional context**
No other additional context

**Comment by resmo** [comment]
trying to reproduce.

**Comment by resmo** [comment]
I was able to reproduce, working on a fix

**Comment by resmo** [comment]
Thanks for reporting this issue @Lvl4Sword , a fix is on the way #70

**Comment by resmo** [comment]
closed by #70
