### ISSUE TITLE
[Feature] - Ability to Reboot Instance(s)

### ISSUE THREAD

**Issue by Lvl4Sword** [vultr/ansible-collection-vultr#71]
**Is your feature request related to a problem? Please describe.**
When removing UFW and doing `iptables -F`, this will drop the SSH connection.
I'd like to be able to reboot the instance(s) ( https://www.vultr.com/api/#tag/instances/operation/reboot-instance / https://www.vultr.com/api/#tag/instances/operation/reboot-instances ) via the API and do a hard reset, as this is the only option you've got after removing UFW.

**Describe the solution you'd like**
Ability to hard reset ( https://www.vultr.com/api/#tag/instances/operation/reboot-instance / https://www.vultr.com/api/#tag/instances/operation/reboot-instances ) via the API

**Describe alternatives you've considered**
There aren't any

**Additional context**
No additional context

**Comment by resmo** [comment]
have you tried `state=restarted`?
