### ISSUE TITLE
[Feature] - bare metal support 

### ISSUE THREAD

**Issue by sonnysighedup** [vultr/ansible-collection-vultr#78]
**Describe the bug**
vultr.cloud is unable to create bare metal instances (perhaps due to the swtich to the v2 api?)

**To Reproduce**
Run a playbook with "plan: vbm-6c-32gb" (or another bare metal offering).

**Screenshots**
TASK [vultr : create an instance using OS] ************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "fetch_url_info": {"body": "{\"error\":\"Invalid plan chosen.\",\"status\":400}", "connection": "close", "content-type": "application/json", "date": "Tue, 08 Aug 2023 04:47:10 GMT", "msg": "HTTP Error 400: Bad Request", "server": "nginx", "status": 400, "strict-transport-security": "max-age=63072000", "transfer-encoding": "chunked", "url": "https://api.vultr.com/v2/instances", "x-content-type-options": "nosniff", "x-frame-options": "DENY", "x-robots-tag": "noindex,noarchive", "x-user": "sonnysighedup@xxxxx.xxx"}, "msg": "Failure while calling the Vultr API v2 with POST for \"/instances\"."}

**Additional context**

I can manually create a bare metal instance on the vultr website or through vultr-cli. 

Bare metals need to be created with [a POST resquest for /bare_metals](https://www.vultr.com/api/#operation/create-baremetal), so requests to /instances won't work.

**Comment by resmo** [comment]
Hi @sonnysighedup

This module is only for cloud instances. We started the development of the bare_metal module in #79

**Comment by resmo** [comment]
closed by #79
